ad in,unimage

diff --git a/templates/tmp_image/buildimage.tmpl b/templates/tmp_image/buildimage.tmpl
--- a/templates/tmp_image/buildimage.tmpl
+++ b/templates/tmp_image/buildimage.tmpl
@@ -11,7 +11,7 @@ echo "🔍 Checking..."
 
 echo "ตรวจเช็คไฟล์"
 sleep 1
-[ -f "icon.png" ] || { echo "❌ icon.png missing"; exit 1; }
+[ -f "/icons/icon-256.png" ] || { echo "❌ /icons/icon-256.png missing"; exit 1; }
 [ -f "main.go" ] || { echo "❌ main.go missing"; exit 1; }
 [ -f "go.mod" ] || { echo "❌ go.mod missing"; exit 1; }
 [ -f "go.sum" ] || { echo "❌ go.sum, missing"; exit 1; }
@@ -43,10 +43,13 @@ Icon=$EXEC
 Type=Application
 Categories={{.Categories}}
 Terminal=false
+StartupWMClass=$APP
 EOF
 
 cp icon.png $APP.AppDir/$EXEC.png
 cp icon.png $APP.AppDir/.DirIcon
+cp installappImage.sh $APP.AppDir
+cp UninstallappImage.sh $APP.AppDir
 
 echo "🚀 pack..."
 ./appimagetool-x86_64.AppImage $APP.AppDir
